### ISSUE TITLE
[Suggestion]  Lore

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/Issues-EpicBackpacks#4]
Ability to have Lore on Backpacks.

**Comment by LoneDev6** [comment]
hello!
it's already possible, if you have any problem please answer here again.

Have a nice day


example:
```yml
  example_1:
    enabled: true
    display_name: '&fexample'
    can_auto_pickup: false
    item:
      type: HEAD
      texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmEzYjM0ODYyYjlhZmI2M2NmOGQ1Nzc5OTY2ZDNmYmE3MGFmODJiMDRlODNmM2VhZjY0NDlhZWJhIn19fQ=='
      lore:
        - "&6[ &ePortable Backpack &6]"
        - "&fYou can store any item."
    size: 2
    blacklist:
      - BARRIER
      - BEDROCK
    craft_recipe:
      amount: 4
      pattern:
        - XOX
        - XEX
        - XOX
      ingredients:
        O: OBSIDIAN
        E: ENDER_CHEST
```
